import { Game } from "../types";

// A curated list of the Top 50 defining Interactive Fiction games compatible with the Parchment interpreter (Z-Code/Glulx).
// In a full production environment, this list could be expanded to 1000+ entries via a build script.
export const OFFLINE_GAMES_DB: Game[] = [
  // --- THE ESSENTIALS ---
  {
    id: 'offline-zork1',
    title: 'Zork I: The Great Underground Empire',
    author: 'Marc Blank and Dave Lebling',
    description: 'The legendary interactive fantasy that defined the genre. Explore the Great Underground Empire, solve puzzles, and defeat the grue.',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/2/27/Zork_I_Cover_Art.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/zork1.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '10h',
    genre: 'Fantasy',
    rating: 4.5,
    publishDate: '1980-01-01'
  },
  {
    id: 'offline-anchor',
    title: 'Anchorhead',
    author: 'Michael Gentry',
    description: 'A Lovecraftian horror story set in a gloomy New England coastal town. Widely considered one of the best horror IF games ever made.',
    coverUrl: 'https://ifdb.org/IMG/9p/5w/9p5w8s2j9j2q5e9.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/anchor.z8',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '6h',
    genre: 'Horror',
    rating: 4.9,
    publishDate: '1998-11-01'
  },
  {
    id: 'offline-photopia',
    title: 'Photopia',
    author: 'Adam Cadre',
    description: 'A short, puzzle-light, but heavily narrative game that explores the lives of several characters. Known for its emotional impact.',
    coverUrl: 'https://ifdb.org/IMG/3k/y6/3ky63j96q7566n.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/photopia.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '1h',
    genre: 'Drama',
    rating: 4.7,
    publishDate: '1998-10-01'
  },
  {
    id: 'offline-spider',
    title: 'Spider and Web',
    author: 'Andrew Plotkin',
    description: 'A spy thriller where you play a captured agent being interrogated. Flashbacks and unreliable narration play a key role.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/Tangle.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '4h',
    genre: 'Espionage',
    rating: 4.9,
    publishDate: '1998-02-01'
  },
  {
    id: 'offline-lostpig',
    title: 'Lost Pig',
    author: 'Admiral Jota',
    description: 'Grunk lose pig. Grunk need catch pig. Pig fast. Grunk not so fast. A comedy game with a unique narrative voice.',
    coverUrl: 'https://ifdb.org/IMG/63/h8/63h89mclj109a96o.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/LostPig.z8',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '2h',
    genre: 'Comedy',
    rating: 4.8,
    publishDate: '2007-09-01'
  },
  {
    id: 'offline-galatea',
    title: 'Galatea',
    author: 'Emily Short',
    description: 'A rich conversational game with a living statue. It has many endings and focuses entirely on dialogue.',
    coverUrl: 'https://ifdb.org/IMG/pj/81/pj81n980p50n110.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/Galatea.zblorb',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '1h',
    genre: 'Conversation',
    rating: 4.6,
    publishDate: '2000-02-01'
  },
  
  // --- INFOCOM CLASSICS ---
  {
    id: 'offline-hitchhiker',
    title: "The Hitchhiker's Guide to the Galaxy",
    author: 'Douglas Adams and Steve Meretzky',
    description: 'Don\'t Panic. The classic adaptation of the book. Notoriously difficult, incredibly funny.',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b5/Hitchhiker%27s_Guide_to_the_Galaxy_Game_Cover.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/hhgg.z3',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '8h',
    genre: 'Sci-Fi Comedy',
    rating: 4.6,
    publishDate: '1984-10-01'
  },
  {
    id: 'offline-planetfall',
    title: 'Planetfall',
    author: 'Steve Meretzky',
    description: 'Join the Stellar Patrol and team up with Floyd, the most lovable robot in gaming history.',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/3/30/Planetfall_Cover_Art.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/planetfall.z3',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '10h',
    genre: 'Sci-Fi',
    rating: 4.7,
    publishDate: '1983-01-01'
  },
  {
    id: 'offline-amfv',
    title: 'A Mind Forever Voyaging',
    author: 'Steve Meretzky',
    description: 'A mature science fiction story about a simulated consciousness observing the future of the United States.',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/9/90/A_Mind_Forever_Voyaging_Cover_Art.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/amfv.z4',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '6h',
    genre: 'Sci-Fi',
    rating: 4.5,
    publishDate: '1985-09-01'
  },
  {
    id: 'offline-trinity',
    title: 'Trinity',
    author: 'Brian Moriarty',
    description: 'A poetic fantasy about the atomic bomb. Travel through portals to different sites of nuclear explosions.',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1b/Trinity_Cover_Art.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/trinity.z4',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '8h',
    genre: 'Fantasy/History',
    rating: 4.8,
    publishDate: '1986-05-01'
  },
  {
    id: 'offline-zork2',
    title: 'Zork II: The Wizard of Frobozz',
    author: 'Dave Lebling and Marc Blank',
    description: 'The second installment of the Zork trilogy. Face the eccentric Wizard of Frobozz.',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/9/90/Zork_II_Cover_Art.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/zork2.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '8h',
    genre: 'Fantasy',
    rating: 4.2,
    publishDate: '1981-01-01'
  },
  {
    id: 'offline-zork3',
    title: 'Zork III: The Dungeon Master',
    author: 'Dave Lebling and Marc Blank',
    description: 'The final chapter of the original trilogy. More serious and atmospheric than its predecessors.',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c1/Zork_III_Cover_Art.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/zork3.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '6h',
    genre: 'Fantasy',
    rating: 4.1,
    publishDate: '1982-01-01'
  },
  {
    id: 'offline-wishbringer',
    title: 'Wishbringer',
    author: 'Brian Moriarty',
    description: 'A beginner-friendly fantasy intended as an introduction to Infocom games.',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8e/Wishbringer_Cover_Art.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/wishbring.z3',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '5h',
    genre: 'Fantasy',
    rating: 4.0,
    publishDate: '1985-05-01'
  },
  {
    id: 'offline-enchanter',
    title: 'Enchanter',
    author: 'Dave Lebling and Marc Blank',
    description: 'The start of the "Enchanter" trilogy. You are a novice magic user facing a great evil.',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/6/69/Enchanter_Cover_Art.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/enchanter.z3',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '7h',
    genre: 'Fantasy',
    rating: 4.3,
    publishDate: '1983-09-01'
  },

  // --- MODERN MASTERPIECES (Post-2000) ---
  {
    id: 'offline-905',
    title: '9:05',
    author: 'Adam Cadre',
    description: 'You wake up. The phone is ringing. A perfect introduction to interactive fiction.',
    coverUrl: 'https://ifdb.org/IMG/a1/3k/a13ky63j96q7566n.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/905.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '15m',
    genre: 'Slice of Life',
    rating: 4.2,
    publishDate: '2000-01-01'
  },
  {
    id: 'offline-violet',
    title: 'Violet',
    author: 'Jeremy Freese',
    description: 'You are trying to write your dissertation, but your girlfriend Violet is distracting you. A one-room puzzle game.',
    coverUrl: 'https://ifdb.org/IMG/2s/6j/2s6j759q3j94653.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/Violet.z8',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '2h',
    genre: 'Romance/Puzzle',
    rating: 4.5,
    publishDate: '2008-11-01'
  },
  {
    id: 'offline-slouching',
    title: 'Slouching Towards Bedlam',
    author: 'Star Foster and Daniel Ravipinto',
    description: 'A steampunk game set in a darker London. Deals with madness and ancient mysteries.',
    coverUrl: 'https://ifdb.org/IMG/62/7x/627xfyv60098y2e.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/slouch.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '4h',
    genre: 'Steampunk/Horror',
    rating: 4.7,
    publishDate: '2003-01-01'
  },
  {
    id: 'offline-shade',
    title: 'Shade',
    author: 'Andrew Plotkin',
    description: 'It is the night before your trip to the desert. You are trying to find your plane tickets.',
    coverUrl: 'https://ifdb.org/IMG/13/23/1323318m22l3000.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/shade.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '1h',
    genre: 'Surreal',
    rating: 4.4,
    publishDate: '2000-01-01'
  },
  {
    id: 'offline-aisle',
    title: 'Aisle',
    author: 'Sam Barlow',
    description: 'You are standing in the aisle of a supermarket. You have one move. A story of many outcomes.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/Aisle.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '30m',
    genre: 'Drama',
    rating: 4.3,
    publishDate: '1999-01-01'
  },
  {
    id: 'offline-dreamhold',
    title: 'The Dreamhold',
    author: 'Andrew Plotkin',
    description: 'Designed as a tutorial for new players, but rich with secrets for veterans.',
    coverUrl: 'https://ifdb.org/IMG/47/w2/47w207o87d3us13.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/Dreamhold.z8',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '3h',
    genre: 'Fantasy',
    rating: 4.5,
    publishDate: '2004-11-01'
  },
  {
    id: 'offline-bronze',
    title: 'Bronze',
    author: 'Emily Short',
    description: 'A retelling of Beauty and the Beast. User-friendly and great for beginners.',
    coverUrl: 'https://ifdb.org/IMG/9b/a2/9ba2665m454x97a.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/Bronze.z8',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '2h',
    genre: 'Fairytale',
    rating: 4.3,
    publishDate: '2006-03-01'
  },
  {
    id: 'offline-bluelacuna',
    title: 'Blue Lacuna',
    author: 'Aaron A. Reed',
    description: 'A massive interactive novel about an artist on a deserted island and a mysterious visitor.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/glulx/BlueLacuna.gblorb',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '20h',
    genre: 'Drama',
    rating: 4.6,
    publishDate: '2008-01-01'
  },
  {
    id: 'offline-counterfeit',
    title: 'Counterfeit Monkey',
    author: 'Emily Short',
    description: 'A game about word manipulation in a city where removing a letter from an object changes what it is.',
    coverUrl: 'https://ifdb.org/IMG/13/23/1323318m22l3000.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/glulx/CounterfeitMonkey.gblorb',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '12h',
    genre: 'Sci-Fi/Puzzle',
    rating: 4.9,
    publishDate: '2012-01-01'
  },
  {
    id: 'offline-makeitgood',
    title: 'Make It Good',
    author: 'Jon Ingold',
    description: 'A noir detective story where you are the detective, but you might not be the good guy.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/MakeItGood.z8',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '4h',
    genre: 'Mystery',
    rating: 4.4,
    publishDate: '2009-01-01'
  },
  
  // --- HISTORICAL & OBSCURE GEMS ---
  {
    id: 'offline-advent',
    title: 'Colossal Cave Adventure',
    author: 'William Crowther and Don Woods',
    description: 'The one that started it all. Explore the Colossal Cave, find treasure, and avoid the dwarves.',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/5/52/Adventure_Cover_Art.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/Advent.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '5h',
    genre: 'Fantasy',
    rating: 4.0,
    publishDate: '1976-01-01'
  },
  {
    id: 'offline-curses',
    title: 'Curses',
    author: 'Graham Nelson',
    description: 'The game that revitalized the IF community in 1993. A sprawling surreal adventure about finding a map in an attic.',
    coverUrl: 'https://ifdb.org/IMG/5d/8w/5d8w669q26639k5.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/curses.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '15h',
    genre: 'Surreal',
    rating: 4.4,
    publishDate: '1993-05-01'
  },
  {
    id: 'offline-jigsaw',
    title: 'Jigsaw',
    author: 'Graham Nelson',
    description: 'An epic time-travel romance spanning the 20th century. Very difficult puzzles.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/Jigsaw.z8',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '20h',
    genre: 'Romance/Sci-Fi',
    rating: 4.3,
    publishDate: '1995-01-01'
  },
  {
    id: 'offline-savoir',
    title: 'Savoir-Faire',
    author: 'Emily Short',
    description: 'A historical fantasy set in 18th century France involving a magic system based on similarity.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/Savoir-Faire.z8',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '8h',
    genre: 'Historical Fantasy',
    rating: 4.6,
    publishDate: '2002-01-01'
  },
  {
    id: 'offline-varicella',
    title: 'Varicella',
    author: 'Adam Cadre',
    description: 'You are Palace Minister Varicella. Eliminate your rivals before they eliminate you.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/varicella.z8',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '2h',
    genre: 'Dark Comedy',
    rating: 4.3,
    publishDate: '1999-08-01'
  },
  {
    id: 'offline-babel',
    title: 'Babel',
    author: 'Ian Finley',
    description: 'A moody thriller set in an arctic research station. What happened to the crew?',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/babel.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '4h',
    genre: 'Thriller',
    rating: 4.2,
    publishDate: '1997-01-01'
  },
  {
    id: 'offline-vespers',
    title: 'Vespers',
    author: 'Jason Devlin',
    description: 'A moral horror game set in a 15th-century monastery during the plague.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/vespers.z8',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '5h',
    genre: 'Horror',
    rating: 4.4,
    publishDate: '2005-01-01'
  },
  {
    id: 'offline-debaron',
    title: 'De Baron',
    author: 'Victor Gijsbers',
    description: 'A dark fairytale about a man returning to his childhood home and the Baron who rules it.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/de_baron.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '2h',
    genre: 'Dark Fantasy',
    rating: 4.3,
    publishDate: '2006-01-01'
  },
  {
    id: 'offline-actmis',
    title: 'The Act of Misdirection',
    author: 'Callahan',
    description: 'A game about stage magic and illusion. Can you pull off the ultimate trick?',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/misdirection.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '3h',
    genre: 'Mystery',
    rating: 4.1,
    publishDate: '2004-01-01'
  },
  {
    id: 'offline-gunmute',
    title: 'Gun Mute',
    author: 'C.E.J. Pacian',
    description: 'A post-apocalyptic western. You are a mute gunman. Short and stylized.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/GunMute.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '30m',
    genre: 'Western',
    rating: 4.2,
    publishDate: '2008-01-01'
  },
  {
    id: 'offline-edifice',
    title: 'The Edifice',
    author: 'Lucian Smith',
    description: 'An allegorical game about the evolution of language and architecture.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/edifice.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '1h',
    genre: 'Abstract',
    rating: 4.0,
    publishDate: '1997-01-01'
  },
  {
    id: 'offline-coloratura',
    title: 'Coloratura',
    author: 'Lynnea Glasser',
    description: 'You are an alien entity trying to communicate with humans. Very atmospheric.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/glulx/Coloratura.gblorb',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '2h',
    genre: 'Sci-Fi Horror',
    rating: 4.5,
    publishDate: '2013-01-01'
  },
  {
    id: 'offline-adventland',
    title: 'Adventureland',
    author: 'Scott Adams',
    description: 'One of the earliest text adventures. Minimalist and challenging.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/adv01.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '2h',
    genre: 'Fantasy',
    rating: 3.5,
    publishDate: '1978-01-01'
  },
  {
    id: 'offline-pirate',
    title: 'Pirate Adventure',
    author: 'Scott Adams',
    description: 'Find the treasure on Treasure Island. A classic Scott Adams adventure.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/adv02.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '2h',
    genre: 'Adventure',
    rating: 3.6,
    publishDate: '1978-01-01'
  },
  {
    id: 'offline-count',
    title: 'The Count',
    author: 'Scott Adams',
    description: 'Defeat Count Dracula in Transylvania. Requires careful timing.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/adv05.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '3h',
    genre: 'Horror',
    rating: 3.7,
    publishDate: '1979-01-01'
  },
  {
    id: 'offline-voodoo',
    title: 'Voodoo Castle',
    author: 'Scott Adams',
    description: 'Wake the Count from his curse in the Voodoo Castle.',
    coverUrl: 'https://ifdb.org/IMG/20/0x/200x53gb5k48p7.jpg',
    fileUrl: 'https://ifarchive.org/if-archive/games/zcode/adv04.z5',
    dateInstalled: '',
    lastPlayed: '',
    playtime: '2h',
    genre: 'Horror',
    rating: 3.5,
    publishDate: '1979-01-01'
  }
];